âœ“ WandB initialized in Online mode
The Iteration0:
================================
Epoch:0 | AvgLoss:0.6923 | ReconLoss:0.0338
Epoch:1 | AvgLoss:0.6922 | ReconLoss:0.0338
Epoch:2 | AvgLoss:0.6921 | ReconLoss:0.0338
Epoch:3 | AvgLoss:0.6919 | ReconLoss:0.0338
Epoch:4 | AvgLoss:0.6915 | ReconLoss:0.0338
Epoch:5 | AvgLoss:0.6910 | ReconLoss:0.0338
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/exit_hooks.py", line 52, in exc_handler
    traceback.print_exception(exc_type, exc, tb)
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
